class ArgumentError(Exception):
    pass

# So here we just have a more specific type name, but it still just behaves like any other Exceptions
